# Project information
site_name: Future Makers STEAM Course Kit
site_description: The Future Makers is the open source course kit for STEAM education.
copyright: Copyright &copy; All rights reserved. 2017 - 2024 Beets Limited
site_url: https://futuremakers.beets3d.com/
repo_url: https://github.com/beets3d/FutureMakers
# extra_css:
#   - assets/stylesheets/extra.css

# extra_javascript:
#   - assets/javascripts/extra.js

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.tabs
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/beets-logo-square.avif
  favicon: images/favicon.ico
  static_templates:
    - sitemap.xml
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  extra:
    homepage: https://futuremakers.beets3d.com/
    author: true
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  toc_depth: 3

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/beets3d/FutureMakers
      name: FutureMakers on Github
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to enhance quality of docs content, analyse site effectiveness and needs. 
      By consenting, you help us improve our website. Thanks!
  generator: false

markdown_extensions:
  - tables
  # Enables admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - md_in_html
  - toc:
      permalink: ¶
      toc_depth: 4


plugins:
  - glightbox
  - awesome-nav
  - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        num_workers: 2
  - search:
      lang:
        - en
        - zh_HK
  - tags:
      tags_file: tags.md
  - ultralytics:  # to enhance SEO by adding metadata
      verbose: True
      enabled: True
      default_author: "Beets Limited"
      add_desc: True
      add_image: True
      add_keywords: True
      add_share_buttons: False
      add_authors: False
      add_json_ld: False
      add_css: True
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "Future Makers: Hands-On STEAM Projects Kit"
        - locale: zh_HK 
          name: 繁體中文 (香港)
          build: true
          site_name: "未來創客: 動手做STEAM專案套裝"
          nav_translations:
            Home: 首页
            Projects: 專案
            Resources: 資源
            Reference: 參考
            Glossary: 詞彙表
            Lesson 1: 第一課
            Overview: 概覽
            Handbook: 指南
            Lesson Plan: 教案
            Exercise Cards: 練習卡
            Teaching Tips: 教學提示
            Materials: 材料
          nav_translations:
            Home: 首頁
            Projects: 專案
            Resources: 資源
            Reference: 參考
            Glossary: 詞彙表
            Lesson 1: 第一課
            Overview: 概覽
            Handbook: 指南
            Lesson Plan: 教案
            Exercise Cards: 練習卡
            Teaching Tips: 教學提示
            Materials: 材料
            Additional Concepts: 附加概念
            Assembly Guide: 組裝指南
            Gait Diagramming: 步態圖示
            Teeter-Totter Test: 翹翹板測試
            Concepts of Walking: 行走概念
            Optional Microbit: 附加Microbit
            Original Character: 原創角色
            AI×3D Modeling: AI×3D建模
  
extra_css:
  - assets/stylesheets/extra.css
